source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZJPhotoPod_Example', :exclusive => true do
  pod 'ZJPhotoPod', :path => '../'
end

target 'ZJPhotoPod_Tests', :exclusive => true do
  pod 'ZJPhotoPod', :path => '../'

  
end
